apiVersion: batch/v1
kind: Job
metadata:
  name: raw-output-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: client
        image: bazel/pipeline/src/main/java/ai/promoted/metrics/logprocessor/job/raw:RawOutputJob_image
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: jobmanager
        # If you want to restart from a savepoint, add this after "run" ["-s", "s3a://promoted-event-logs/savepoints/savepoint-{id}"]
        command: ["flink", "run", "-d", "/opt/RawOutputJob_deploy.jar"]
        args: [
          "--s3Bucket=promoted-event-logs",
          "--jobLabel=blue",
          "--sideOutputDebugLogging",
          "--startFromEarliest",

          "--parallelism=1",
          "--maxParallelism=1",
          "--logParquet",

          # For local development, we want to periodically update the watermark.
          "--procAndEventWatermarkGenerator",
          "--watermarkIdlenessProcessingTimeTrailingDuration=PT1M",
          "--checkpointInterval=PT1M",
        ]
        # We use specific mounts so we can map in log4j-cli.properties.
        # Otherwise, we need to modify the Helm chart directly.
        # Long-term, we the Flink client jobs should not reuse the config map.
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: flink-config
          mountPath: /opt/flink/conf/flink-conf-taskmanager.yaml
          subPath: flink-conf-taskmanager.yaml
        - name: flink-config
          mountPath: /opt/flink/conf/log4j.properties
          subPath: log4j.properties
        - name: flink-config
          mountPath: /opt/flink/conf/security.properties
          subPath: security.properties
        - name: flink-cli-config
          mountPath: /opt/flink/conf/log4j-cli.properties
          subPath: log4j-cli.properties
      restartPolicy: Never
      serviceAccountName: ""
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
          items:
            - key: flink-conf.yaml
              path: flink-conf.yaml
            - key: flink-conf-taskmanager.yaml
              path: flink-conf-taskmanager.yaml
            - key: log4j.properties
              path: log4j.properties
            - key: security.properties
              path: security.properties
      - name: flink-cli-config
        configMap:
          name: flink-cli-config
          items:
            - key: log4j-cli.properties
              path: log4j-cli.properties
status: {}
